//=============================================================================
const express = require('express');
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
/* Підключення бібліотек JavaScript */
var fs = require('fs');

eval(fs.readFileSync('./utils/IIT-library-util/lib/euscpt.js')+'');
eval(fs.readFileSync('./utils/IIT-library-util/lib/euscpm.js')+'');
eval(fs.readFileSync('./utils/IIT-library-util/lib/euscp.js')+'');

//=============================================================================

/* Налаштування серверів ЦСК */
var g_CAs = "./utils/IIT-library-util/data/CAs.Test.json"

/* Масив з шляхом до кореневих сертификатів ЦЗО та ЦСК */
var g_CACerts = [
	"./utils/IIT-library-util/data/CACertificates.Test.p7b",
];

/* Налаштування ЦСК за замовчанням */
var g_CADefaultSettings = {
	"issuerCNs": 				["Акредитований центр сертифікації ключів ІДД ДФС",
								"Акредитований центр сертифікації ключів ІДД Міндоходів",
								"Акредитований центр сертифікації ключів ІДД ДПС"],
	"address": 					"acskidd.gov.ua",
	"ocspAccessPointAddress":	"acskidd.gov.ua/services/ocsp/",
	"ocspAccessPointPort":		"80",
	"cmpAddress":				"acskidd.gov.ua",
	"tspAddress":				"acskidd.gov.ua",
	"tspAddressPort":			"80",
	"directAccess":				true
};

//-----------------------------------------------------------------------------

/* Налаштування ос. ключа */
var g_PKey = {
	filePath: "./utils/IIT-library-util/data/Key-6.dat",	/* Шлях до файлу з ос. ключем */
	password: "12345677",			/* Пароль до файлу з ос. ключем */
	certificates: [			/* Масив з шляхами до файлів сертифікатів ос. ключа */
	],
	CACommonName: "Тестовий ЦСК АТ \"ІІТ\"" /*Ім'я ЦСК, що видав сертифікат ос. ключа*/
};

//-----------------------------------------------------------------------------

var g_euSign = null;
var g_isLibraryLoaded = false;

//=============================================================================

/* Ініціалізація налаштувань криптографічної бібліотеки */
function SetSettings(CAs, CASettings) {
	var offline = true;
	var useOCSP = false;
	var useCMP = false;

	offline = ((CASettings == null) ||
		(CASettings.address == "")) ?
		true : false;
	useOCSP = (!offline && (CASettings.ocspAccessPointAddress != ""));
	useCMP = (!offline && (CASettings.cmpAddress != ""));

	g_euSign.SetJavaStringCompliant(true);

	var settings = g_euSign.CreateFileStoreSettings();
	settings.SetPath('');
	settings.SetSaveLoadedCerts(false);
	g_euSign.SetFileStoreSettings(settings);

	settings = g_euSign.CreateModeSettings();
	settings.SetOfflineMode(offline);
	g_euSign.SetModeSettings(settings);

	settings = g_euSign.CreateProxySettings();
	g_euSign.SetProxySettings(settings);

	settings = g_euSign.CreateTSPSettings();
	settings.SetGetStamps(!offline);
	if (!offline) {
		if (CASettings.tspAddress != "") {
			settings.SetAddress(CASettings.tspAddress);
			settings.SetPort(CASettings.tspAddressPort);
		} else if (g_CADefaultSettings){
			settings.SetAddress(g_CADefaultSettings.tspAddress);
			settings.SetPort(g_CADefaultSettings.tspAddressPort);
		}
	}
	g_euSign.SetTSPSettings(settings);

	settings = g_euSign.CreateOCSPSettings();
	if (useOCSP) {
		settings.SetUseOCSP(true);
		settings.SetBeforeStore(true);
		settings.SetAddress(CASettings.ocspAccessPointAddress);
		settings.SetPort("80");
	}
	g_euSign.SetOCSPSettings(settings);

	settings = g_euSign.CreateOCSPAccessInfoModeSettings();
	settings.SetEnabled(true);
	g_euSign.SetOCSPAccessInfoModeSettings(settings);
	settings = g_euSign.CreateOCSPAccessInfoSettings();
	for (var i = 0; i < CAs.length; i++) {
		settings.SetAddress(CAs[i].ocspAccessPointAddress);
		settings.SetPort(CAs[i].ocspAccessPointPort);

		for (var j = 0; j < CAs[i].issuerCNs.length; j++) {
			settings.SetIssuerCN(CAs[i].issuerCNs[j]);
			g_euSign.SetOCSPAccessInfoSettings(settings);
		}
	}

	settings = g_euSign.CreateCMPSettings();
	settings.SetUseCMP(useCMP);
	if (useCMP) {
		settings.SetAddress(CASettings.cmpAddress);
		settings.SetPort("80");
	}
	g_euSign.SetCMPSettings(settings);

	settings = g_euSign.CreateLDAPSettings();
	g_euSign.SetLDAPSettings(settings);
}

//-----------------------------------------------------------------------------

/* Імпорт сертифікатів до сховища криптографічної бібліотеки */
function LoadCertificates(certsFilePathes) {
	if (!certsFilePathes)
		return;

	for (var i = 0; i < certsFilePathes.length; i++) {
		var path = certsFilePathes[i];
		var data = new Uint8Array(fs.readFileSync(path));
		if (path.substr(path.length - 3) == 'p7b') {
			g_euSign.SaveCertificates(data);
		} else {
			g_euSign.SaveCertificate(data);
		}
	}
}

//-----------------------------------------------------------------------------

/* Зчитування особистого ключа */
/* Ос. ключ використовується в функціях накладання підпису, зашифрування та */
/* розшифрування даних */
function ReadPrivateKey(pKeyFilePath, password, certsFilePathes) {
	/* Імпорт сертифікатів ос. ключа */
	LoadCertificates(certsFilePathes);
	/* Зчитування ключа */
	var pKeyData = new Uint8Array(fs.readFileSync(pKeyFilePath));
	g_euSign.ReadPrivateKeyBinary(pKeyData, password)
}

//-----------------------------------------------------------------------------

/* Ініціалізація криптографічної бібліотеки та встановлення налаштувань */
function Initialize(readPrivKey) {
	/* Перевірка необхідності ініціалізації криптографічної бібліотеки */
	if (!g_euSign.IsInitialized()) {
		/* Ініціалізація криптографічної бібліотеки */
		g_euSign.Initialize();
	}

	/* Перевірка необхідності встановлення налаштувань крипт. бібліотеки */
	if (g_euSign.DoesNeedSetSettings()) {
		/* Зчитування файлу з налаштуваннями ЦСК */
		var CAs = JSON.parse(fs.readFileSync(g_CAs), 'utf8');

		/* Отримання налаштувань ЦСК для ос. ключа */
		var CASettings = null;
		for (var i = 0; i < CAs.length; i++) {
			for (var j = 0; j < CAs[i].issuerCNs.length; j++) {
				if (g_PKey.CACommonName == CAs[i].issuerCNs[j]) {
					CASettings = CAs[i];
					break;
				}
			}

			if (CASettings)
				break;
		}

		/* Встановлення параметрів за замовчанням */
		SetSettings(CAs, CASettings);

		/* Завантаження сертифікатів ЦСК */
		LoadCertificates(g_CACerts);
	}

	if (readPrivKey) {
		/* Перевірка чи зчитано ос. ключ */
		if (!g_euSign.IsPrivateKeyReaded()) {
			/* Зчитування ос. ключа */
			ReadPrivateKey(g_PKey.filePath, g_PKey.password,
				g_PKey.certificates);
		}
	}
}


function VerifyHash(hash, sign) {
	if (!g_isLibraryLoaded)
		throw "Library not loaded";

	Initialize(false);

	return g_euSign.VerifyHash(hash, sign);
}


//=============================================================================

/* Функція викликається після завантаження бібліотеки */
/* Функції бібліотеки можна викликати тільки після виклику EUSignCPModuleInitialized */
function EUSignCPModuleInitialized(isInitialized) {
	console.log('*******************************')
	g_isLibraryLoaded = isInitialized;
	console.log(isInitialized);

	/* Приклад відображення інф. про підпис */
	var _printSignInfo = function(signInfo) {
		var signerInfo = signInfo.GetOwnerInfo();
		var signTimeInfo = signInfo.GetTimeInfo();
		console.log("Sign info:");
		console.log("Signer info:");
		console.log("\tSubject CN:" + signerInfo.GetSubjCN());
		console.log("\tCA:" + signerInfo.GetIssuerCN());
		console.log("\tSN:" + signerInfo.GetSerial());

		if (signTimeInfo.IsTimeAvail()) {
			console.log((signTimeInfo.IsTimeStamp() ?
				"\tTime stamp (from data):" :
				"\tSign time:") + signTimeInfo.GetTime());
		} else {
			console.log("\tSign time: not available");
		}

		if (signTimeInfo.IsSignTimeStampAvail()) {
			console.log("\tTime stamp (from sign):" +
				signTimeInfo.GetSignTimeStamp());
		}
	}
}

//=============================================================================

var g_euSign = EUSignCP();

//=============================================================================


app.post('/', function (req, res) {
	console.log(`Start IIT function VerifyHashSign`);

	let { hash, signature } = req.body;


	try {
		// let b64string = 'eyJzaWduZWRJdGVtcyI6W3sibmFtZSI6ImRpYV90ZXN0LmRvY3giLCJzaWduYXR1cmUiOiJNSUkwTlFZSktvWklodmNOQVFjQ29JSTBKakNDTkNJQ0FRRXhEakFNQmdvcWhpUUNBUUVCQVFJQk1Bc0dDU3FHU0liM0RRRUhBYUNDQmtzd2dnWkhNSUlGNzZBREFnRUNBaFErMVFneFlOdkZtd1FBQUFBR1ExZ0FWbStaQURBTkJnc3FoaVFDQVFFQkFRTUJBVENCNFRFV01CUUdBMVVFQ2d3TjBKVFFueUFpMEpUUWh0Q3ZJakZ6TUhFR0ExVUVBd3hxSXRDVTBaYlJqeUl1SU5DYTBMTFFzTkM3MFpiUmhOR1cwTHJRdnRDeTBMRFF2ZEM0MExrZzBMM1FzTkMwMExEUXN0Q3cwWWNnMExYUXU5QzEwTHJSZ3RHQTBMN1F2ZEM5MExqUmhTRFF0TkMrMExMUmx0R0EwWWZRdU5HRklOQy8wTDdSZ2RDNzBZUFFzekVaTUJjR0ExVUVCUk1RVlVFdE5ETXpPVFV3TXpNdE1UQXdNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeU1SY3dGUVlEVlFSaERBNU9WRkpWUVMwME16TTVOVEF6TXpBZUZ3MHlNakE1TURFeU1UQXdNREJhRncweU16QTVNREV5TVRBd01EQmFNSUdjTVRNd01RWURWUVFERENyUXBkQzgwWmJRdTlHTUlOQ1IwTDdRczlDMDBMRFF2U0RRb05DKzBMelFzTkM5MEw3UXN0QzQwWWN4RXpBUkJnTlZCQVFNQ3RDbDBMelJsdEM3MFl3eEtEQW1CZ05WQkNvTUg5Q1IwTDdRczlDMDBMRFF2U0RRb05DKzBMelFzTkM5MEw3UXN0QzQwWWN4R1RBWEJnTlZCQVVURUZSSlRsVkJMVE14T1RjMU1EVTRPVFF4Q3pBSkJnTlZCQVlUQWxWQk1JSHlNSUhKQmdzcWhpUUNBUUVCQVFNQkFUQ0J1VEIxTUFjQ0FnRUJBZ0VNQWdFQUJDRVF2dVBiYXVxZUg0WlhqRVhCSlpUL2xDT1VwOWM0K1JoK1pSVUJjcFQwemdFQ0lRQ0FBQUFBQUFBQUFBQUFBQUFBQUFBQVoxa2hPdkdDNllmVDRYY1VrSDFIRFFRaHRnL1MyTnpvcVRRanhoQWJ5cEhFZWdCK2JEQUxKczFWYkpzT2ZTRHZLU29BQkVDcDF1dEY4VHh3Z29ERWxuc2pIMTZ0OWxqcnBNQTNLUjA0Mld2d0pjcE9GL2pwY2czR0ZiUTZLSmRmQzhIZW8yUTR0V1RxTEJlZjBCSStiYmo2eFhrRUF5UUFCQ0hBZVNFdkxHVjRlTjdJNEtScDc4bkZXMUE0dmQ1Z0Z0R1dXWFRDSnFjLzlBQ2pnZ01wTUlJREpUQXBCZ05WSFE0RUlnUWdWRDFCL3BmR0Z3OVV3VnVqdDRkYkhTc2tTeW1id2k4a3pGcVNPSDVPZXZvd0t3WURWUjBqQkNRd0lvQWd2dFVJTVdEYnhadk4zM0I4RUNrL1dMdHUwbVBHNmxpVDAzZ2JZZlNUdmxjd0RnWURWUjBQQVFIL0JBUURBZ2JBTUJjR0ExVWRKUVFRTUE0R0RDc0dBUVFCZ1pkR0FRRUlIekJKQmdOVkhTQUVRakJBTUQ0R0NTcUdKQUlCQVFFQ0FqQXhNQzhHQ0NzR0FRVUZCd0lCRmlOb2RIUndjem92TDJOaExtbHVabTl5YldwMWMzUXVkV0V2Y21WbmJHRnRaVzUwTHpBSkJnTlZIUk1FQWpBQU1ITUdDQ3NHQVFVRkJ3RURCR2N3WlRBSUJnWUVBSTVHQVFFd0NBWUdCQUNPUmdFRU1Dc0dCZ1FBamtZQkJUQWhNQjhXR1doMGRIQnpPaTh2WTJFdWFXNW1iM0p0YW5WemRDNTFZUzhUQW1WdU1CVUdDQ3NHQVFVRkJ3c0NNQWtHQndRQWkreEpBUUV3Q3dZSktvWWtBZ0VCQVFJQk1CNEdBMVVkRVFRWE1CV2dFd1lLS3dZQkJBR0NOeFFDQTZBRkRBTXlNalF3VHdZRFZSMGZCRWd3UmpCRW9FS2dRSVkrYUhSMGNEb3ZMMk5oTG1sdVptOXliV3AxYzNRdWRXRXZaRzkzYm14dllXUXZZM0pzY3k5RFFTMUNSVVExTURnek1TMUdkV3hzTFZNME1TNWpjbXd3VUFZRFZSMHVCRWt3UnpCRm9FT2dRWVkvYUhSMGNEb3ZMMk5oTG1sdVptOXliV3AxYzNRdWRXRXZaRzkzYm14dllXUXZZM0pzY3k5RFFTMUNSVVExTURnek1TMUVaV3gwWVMxVE5ERXVZM0pzTUlHRkJnZ3JCZ0VGQlFjQkFRUjVNSGN3TWdZSUt3WUJCUVVITUFHR0ptaDBkSEE2THk5allTNXBibVp2Y20xcWRYTjBMblZoTDNObGNuWnBZMlZ6TDI5amMzQXZNRUVHQ0NzR0FRVUZCekFDaGpWb2RIUndPaTh2WTJFdWFXNW1iM0p0YW5WemRDNTFZUzkxY0d4dllXUnpMMk5sY25ScFptbGpZWFJsY3k5a2FXbGhMbkEzWWpCQkJnZ3JCZ0VGQlFjQkN3UTFNRE13TVFZSUt3WUJCUVVITUFPR0pXaDBkSEE2THk5allTNXBibVp2Y20xcWRYTjBMblZoTDNObGNuWnBZMlZ6TDNSemNDOHdTUVlEVlIwSkJFSXdRREFjQmd3cWhpUUNBUUVCQ3dFRUFRRXhEQk1LTXpFNU56VXdOVGc1TkRBZ0Jnd3FoaVFDQVFFQkN3RUVDd0V4RUJNT01UazROekEzTVRndE1EVXdOVGt3RFFZTEtvWWtBZ0VCQVFFREFRRURRd0FFUUptMldRWW14dDl0RHVEc0U0cGpoUTJZYXdLSExmaTY1MXBodVd3MFZVUjB6aTFJMTFJOWdsdklvSWV0VW9BV3E4TzJ2MTZTUm1QMGZwRmxOaGRZNUNneGdpMnZNSUl0cXdJQkFUQ0IrakNCNFRFV01CUUdBMVVFQ2d3TjBKVFFueUFpMEpUUWh0Q3ZJakZ6TUhFR0ExVUVBd3hxSXRDVTBaYlJqeUl1SU5DYTBMTFFzTkM3MFpiUmhOR1cwTHJRdnRDeTBMRFF2ZEM0MExrZzBMM1FzTkMwMExEUXN0Q3cwWWNnMExYUXU5QzEwTHJSZ3RHQTBMN1F2ZEM5MExqUmhTRFF0TkMrMExMUmx0R0EwWWZRdU5HRklOQy8wTDdSZ2RDNzBZUFFzekVaTUJjR0ExVUVCUk1RVlVFdE5ETXpPVFV3TXpNdE1UQXdNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeU1SY3dGUVlEVlFSaERBNU9WRkpWUVMwME16TTVOVEF6TXdJVVB0VUlNV0RieFpzRUFBQUFCa05ZQUZadm1RQXdEQVlLS29Za0FnRUJBUUVDQWFDQ0JnY3dHQVlKS29aSWh2Y05BUWtETVFzR0NTcUdTSWIzRFFFSEFUQWNCZ2txaGtpRzl3MEJDUVV4RHhjTk1qSXdPVEF5TURrd09EUTNXakF2QmdrcWhraUc5dzBCQ1FReElnUWdvTUk4a0c5RzlJbm0xQWhOUHE2QWtqNVZhb3NISnVidVJnVE0rbFpBRmJvd2dnRlJCZ3NxaGtpRzl3MEJDUkFDTHpHQ0FVQXdnZ0U4TUlJQk9EQ0NBVFF3REFZS0tvWWtBZ0VCQVFFQ0FRUWc0ZDl2dUtUbG0vbHpTS0FXdlF1M1llYnRVc1hHUkVMYTZjUmlkVmVrcUlNd2dnRUFNSUhucElIa01JSGhNUll3RkFZRFZRUUtEQTNRbE5DZklDTFFsTkNHMEs4aU1YTXdjUVlEVlFRRERHb2kwSlRSbHRHUElpNGcwSnJRc3RDdzBMdlJsdEdFMFpiUXV0QyswTExRc05DOTBMalF1U0RRdmRDdzBMVFFzTkN5MExEUmh5RFF0ZEM3MExYUXV0R0MwWURRdnRDOTBMM1F1TkdGSU5DMDBMN1FzdEdXMFlEUmg5QzQwWVVnMEwvUXZ0R0IwTHZSZzlDek1Sa3dGd1lEVlFRRkV4QlZRUzAwTXpNNU5UQXpNeTB4TURBd01Rc3dDUVlEVlFRR0V3SlZRVEVSTUE4R0ExVUVCd3dJMEpyUXVOR1gwTEl4RnpBVkJnTlZCR0VNRGs1VVVsVkJMVFF6TXprMU1ETXpBaFErMVFneFlOdkZtd1FBQUFBR1ExZ0FWbStaQURDQ0JFVUdDeXFHU0liM0RRRUpFQUlVTVlJRU5EQ0NCREFHQ1NxR1NJYjNEUUVIQXFDQ0JDRXdnZ1FkQWdFRE1RNHdEQVlLS29Za0FnRUJBUUVDQVRCc0Jnc3Foa2lHOXcwQkNSQUJCS0JkQkZzd1dRSUJBUVlLS29Za0FnRUJBUUlEQVRBd01Bd0dDaXFHSkFJQkFRRUJBZ0VFSUtEQ1BKQnZSdlNKNXRRSVRUNnVnSkkrVldxTEJ5Ym03a1lFelBwV1FCVzZBZ1VBeUs5YlV4Z1BNakF5TWpBNU1ESXdPVEE0TkRkYU1ZSURtRENDQTVRQ0FRRXdnZ0V4TUlJQkZ6RmNNRm9HQTFVRUNneFQwSnpSbHRDOTBaYlJnZEdDMExYUmdOR0IwWUxRc3RDK0lOR0cwTGpSaE5HQTBMN1FzdEMrMFpjZzBZTFJnTkN3MEwzUmdkR0UwTDdSZ05DODBMRFJodEdXMFpjZzBLUFF1dEdBMExEUmw5QzkwTGd4TVRBdkJnTlZCQXNNS05DUTBMVFF2TkdXMEwzUmx0R0IwWUxSZ05DdzBZTFF2dEdBSU5DRzBLTFFvU0RRcHRDWDBKNHhTVEJIQmdOVkJBTU1RTkNtMExYUXZkR0MwWURRc05DNzBZelF2ZEM0MExrZzBMZlFzTkdCMExMUmx0QzAwWWZSZzlDeTBMRFF1OUdNMEwzUXVOQzVJTkMrMFlEUXM5Q3cwTDB4R1RBWEJnTlZCQVVNRUZWQkxUUXpNakl3T0RVeExUSXdNakF4Q3pBSkJnTlZCQVlUQWxWQk1SRXdEd1lEVlFRSERBalFtdEM0MFpmUXNnSVVCZUdlTE5rdW9wa0NBQUFBQVFBQUFPUUFBQUF3REFZS0tvWWtBZ0VCQVFFQ0FhQ0NBZmt3R2dZSktvWklodmNOQVFrRE1RMEdDeXFHU0liM0RRRUpFQUVFTUJ3R0NTcUdTSWIzRFFFSkJURVBGdzB5TWpBNU1ESXdPVEE0TkRkYU1DOEdDU3FHU0liM0RRRUpCREVpQkNCSWpyTDZENlJrb0JtQ1NMU2FPMm9tcFVQRmYxSzZneHhLU2tQNzN5cWJlRENDQVlvR0N5cUdTSWIzRFFFSkVBSXZNWUlCZVRDQ0FYVXdnZ0Z4TUlJQmJUQU1CZ29xaGlRQ0FRRUJBUUlCQkNBdkFEaVFWaUhxNFlNY21abXVhNjY2SG84VWZuT09uQzdnU0djTjZrMEpNekNDQVRrd2dnRWZwSUlCR3pDQ0FSY3hYREJhQmdOVkJBb01VOUNjMFpiUXZkR1cwWUhSZ3RDMTBZRFJnZEdDMExMUXZpRFJodEM0MFlUUmdOQyswTExRdnRHWElOR0MwWURRc05DOTBZSFJoTkMrMFlEUXZOQ3cwWWJSbHRHWElOQ2owTHJSZ05DdzBaZlF2ZEM0TVRFd0x3WURWUVFMRENqUWtOQzAwTHpSbHRDOTBaYlJnZEdDMFlEUXNOR0MwTDdSZ0NEUWh0Q2kwS0VnMEtiUWw5Q2VNVWt3UndZRFZRUURERURRcHRDMTBMM1JndEdBMExEUXU5R00wTDNRdU5DNUlOQzMwTERSZ2RDeTBaYlF0TkdIMFlQUXN0Q3cwTHZSak5DOTBMalF1U0RRdnRHQTBMUFFzTkM5TVJrd0Z3WURWUVFGREJCVlFTMDBNekl5TURnMU1TMHlNREl3TVFzd0NRWURWUVFHRXdKVlFURVJNQThHQTFVRUJ3d0kwSnJRdU5HWDBMSUNGQVhobml6WkxxS1pBZ0FBQUFFQUFBRGtBQUFBTUEwR0N5cUdKQUlCQVFFQkF3RUJCRUFCTjdmMmNEcjBxVzluc1FtVkluVlVQc0pVSmpSdzM5QjROOTZxSWhYSEJGUHlwSnpzcnIyZmE1T2xEaGIycWFyaEp5Q0Q0eTkyd1NjM2lMTDE2NDR2TUEwR0N5cUdKQUlCQVFFQkF3RUJCRUNZNmZOWVR1WEtCTjczSWlEK055YzRPN0N0eUkvV01QVy9HODErbzZUMUVoZEtheVBOUHZTc1N6RWN0L1VNakMrUElSMnNOL05lTmdZUExocmZpemxZb1lJbVBUQ0NKamtHQ3lxR1NJYjNEUUVKRUFJT01ZSW1LRENDSmlRR0NTcUdTSWIzRFFFSEFxQ0NKaFV3Z2lZUkFnRURNUTR3REFZS0tvWWtBZ0VCQVFFQ0FUQnNCZ3NxaGtpRzl3MEJDUkFCQktCZEJGc3dXUUlCQVFZS0tvWWtBZ0VCQVFJREFUQXdNQXdHQ2lxR0pBSUJBUUVCQWdFRUlCTms5SmdLVmEzSzFRdkl2Z1pPUFJGZTQzY0FJWGZid2J0eVZxeW9hVWZUQWdVQXlLOWJmeGdQTWpBeU1qQTVNREl3T1RBNE5EaGFvSUlGdmpDQ0Jib3dnZ1Uyb0FNQ0FRSUNGQVhobml6WkxxS1pBZ0FBQUFFQUFBRGtBQUFBTUEwR0N5cUdKQUlCQVFFQkF3RUJNSUlCRnpGY01Gb0dBMVVFQ2d4VDBKelJsdEM5MFpiUmdkR0MwTFhSZ05HQjBZTFFzdEMrSU5HRzBMalJoTkdBMEw3UXN0QyswWmNnMFlMUmdOQ3cwTDNSZ2RHRTBMN1JnTkM4MExEUmh0R1cwWmNnMEtQUXV0R0EwTERSbDlDOTBMZ3hNVEF2QmdOVkJBc01LTkNRMExUUXZOR1cwTDNSbHRHQjBZTFJnTkN3MFlMUXZ0R0FJTkNHMEtMUW9TRFFwdENYMEo0eFNUQkhCZ05WQkFNTVFOQ20wTFhRdmRHQzBZRFFzTkM3MFl6UXZkQzQwTGtnMExmUXNOR0IwTExSbHRDMDBZZlJnOUN5MExEUXU5R00wTDNRdU5DNUlOQyswWURRczlDdzBMMHhHVEFYQmdOVkJBVU1FRlZCTFRRek1qSXdPRFV4TFRJd01qQXhDekFKQmdOVkJBWVRBbFZCTVJFd0R3WURWUVFIREFqUW10QzQwWmZRc2pBZUZ3MHlNREEyTURNd056UTFNREJhRncweU5UQTJNRE13TnpRMU1EQmFNSUdRTVJZd0ZBWURWUVFLREEzUWxOQ2ZJQ0xRbE5DRzBLOGlNU0l3SUFZRFZRUUREQmxVVTFBdDBZSFF0ZEdBMExMUXRkR0FJQ0xRbE5HVzBZOGlNUmt3RndZRFZRUUZFeEJWUVMwME16TTVOVEF6TXkweU1EQXdNUXN3Q1FZRFZRUUdFd0pWUVRFUk1BOEdBMVVFQnd3STBKclF1TkdYMExJeEZ6QVZCZ05WQkdFTURrNVVVbFZCTFRRek16azFNRE16TUlIeU1JSEpCZ3NxaGlRQ0FRRUJBUU1CQVRDQnVUQjFNQWNDQWdFQkFnRU1BZ0VBQkNFUXZ1UGJhdXFlSDRaWGpFWEJKWlQvbENPVXA5YzQrUmgrWlJVQmNwVDB6Z0VDSVFDQUFBQUFBQUFBQUFBQUFBQUFBQUFBWjFraE92R0M2WWZUNFhjVWtIMUhEUVFodGcvUzJOem9xVFFqeGhBYnlwSEVlZ0IrYkRBTEpzMVZiSnNPZlNEdktTb0FCRUNwMXV0RjhUeHdnb0RFbG5zakgxNnQ5bGpycE1BM0tSMDQyV3Z3SmNwT0YvanBjZzNHRmJRNktKZGZDOEhlbzJRNHRXVHFMQmVmMEJJK2JiajZ4WGtFQXlRQUJDRW5OdXpOUzZKTWxQaG5nci9reVhpM3hMZ0orT05IelRzNm9wUHhldlFCTXdHamdnSkZNSUlDUVRBcEJnTlZIUTRFSWdRZ293Y3ovZUN2Sy9oODNMQ010MFkwRElIQ1dtY1F0WXdITHNEVS9HRnBOY2N3RGdZRFZSMFBBUUgvQkFRREFnYkFNQ0VHQTFVZEpRUWFNQmdHQ0NzR0FRVUZCd01JQmd3ckJnRUVBWUdYUmdFQkNCOHdQQVlEVlIwZ0JEVXdNekF4QmdrcWhpUUNBUUVCQWdJd0pEQWlCZ2dyQmdFRkJRY0NBUllXYUhSMGNITTZMeTlqZW04dVoyOTJMblZoTDJOd2N6QXRCZ05WSFJFRUpqQWtnaEJqWVM1cGJtWnZjbTFxZFhOMExuVmhnUkJqWVVCcGJtWnZjbTFxZFhOMExuVmhNQXdHQTFVZEV3RUIvd1FDTUFBd2NnWUlLd1lCQlFVSEFRTUVaakJrTUFnR0JnUUFqa1lCQVRBSUJnWUVBSTVHQVFRd0tnWUdCQUNPUmdFRk1DQXdIaFlZYUhSMGNITTZMeTlqZW04dVoyOTJMblZoTDJGaWIzVjBFd0psYmpBVkJnZ3JCZ0VGQlFjTEFqQUpCZ2NFQUl2c1NRRUNNQXNHQ1NxR0pBSUJBUUVDQVRBckJnTlZIU01FSkRBaWdDQUY0WjRzMlM2aW1ieDZkbzhIWGF4TXE2U09veVVPWHNCWmpjZ28zNEFScGpCQ0JnTlZIUjhFT3pBNU1EZWdOYUF6aGpGb2RIUndPaTh2WTNwdkxtZHZkaTUxWVM5a2IzZHViRzloWkM5amNteHpMME5hVHkweU1ESXdMVVoxYkd3dVkzSnNNRU1HQTFVZExnUThNRG93T0tBMm9EU0dNbWgwZEhBNkx5OWplbTh1WjI5MkxuVmhMMlJ2ZDI1c2IyRmtMMk55YkhNdlExcFBMVEl3TWpBdFJHVnNkR0V1WTNKc01Ed0dDQ3NHQVFVRkJ3RUJCREF3TGpBc0JnZ3JCZ0VGQlFjd0FZWWdhSFIwY0RvdkwyTjZieTVuYjNZdWRXRXZjMlZ5ZG1salpYTXZiMk56Y0M4d0RRWUxLb1lrQWdFQkFRRURBUUVEYndBRWJCSFIxQlhBUTJCbFg3cGVUdWczSitOZ0VZU2Ryd1ZrQXlDWG5wL1phVXcwSlNQMGNNSHkzSUZocmUxREYweGFoWXBCemd3Y0NPQ1dVZEdKdHlZVFlIVnNoL2lPaGVnclM1YmRMcnpuSW05cjVBdStxZjRlL1lSbERTc3BKK21WcWMvbnpOV09hQnRqVzE5VkNUR0NIOG93Z2gvR0FnRUJNSUlCTVRDQ0FSY3hYREJhQmdOVkJBb01VOUNjMFpiUXZkR1cwWUhSZ3RDMTBZRFJnZEdDMExMUXZpRFJodEM0MFlUUmdOQyswTExRdnRHWElOR0MwWURRc05DOTBZSFJoTkMrMFlEUXZOQ3cwWWJSbHRHWElOQ2owTHJSZ05DdzBaZlF2ZEM0TVRFd0x3WURWUVFMRENqUWtOQzAwTHpSbHRDOTBaYlJnZEdDMFlEUXNOR0MwTDdSZ0NEUWh0Q2kwS0VnMEtiUWw5Q2VNVWt3UndZRFZRUURERURRcHRDMTBMM1JndEdBMExEUXU5R00wTDNRdU5DNUlOQzMwTERSZ2RDeTBaYlF0TkdIMFlQUXN0Q3cwTHZSak5DOTBMalF1U0RRdnRHQTBMUFFzTkM5TVJrd0Z3WURWUVFGREJCVlFTMDBNekl5TURnMU1TMHlNREl3TVFzd0NRWURWUVFHRXdKVlFURVJNQThHQTFVRUJ3d0kwSnJRdU5HWDBMSUNGQVhobml6WkxxS1pBZ0FBQUFFQUFBRGtBQUFBTUF3R0NpcUdKQUlCQVFFQkFnR2dnZ0g1TUJvR0NTcUdTSWIzRFFFSkF6RU5CZ3NxaGtpRzl3MEJDUkFCQkRBY0Jna3Foa2lHOXcwQkNRVXhEeGNOTWpJd09UQXlNRGt3T0RRNFdqQXZCZ2txaGtpRzl3MEJDUVF4SWdRZ0gzeW9Fc3BpRlZUSTR5VUNBYm9LUDZzQ2F6aVpuWkpxdTc4am83WnZ1N0V3Z2dHS0Jnc3Foa2lHOXcwQkNSQUNMekdDQVhrd2dnRjFNSUlCY1RDQ0FXMHdEQVlLS29Za0FnRUJBUUVDQVFRZ0x3QTRrRlloNnVHREhKbVpybXV1dWg2UEZINXpqcHd1NEVobkRlcE5DVE13Z2dFNU1JSUJINlNDQVJzd2dnRVhNVnd3V2dZRFZRUUtERlBRbk5HVzBMM1JsdEdCMFlMUXRkR0EwWUhSZ3RDeTBMNGcwWWJRdU5HRTBZRFF2dEN5MEw3Umx5RFJndEdBMExEUXZkR0IwWVRRdnRHQTBMelFzTkdHMFpiUmx5RFFvOUM2MFlEUXNOR1gwTDNRdURFeE1DOEdBMVVFQ3d3bzBKRFF0TkM4MFpiUXZkR1cwWUhSZ3RHQTBMRFJndEMrMFlBZzBJYlFvdENoSU5DbTBKZlFuakZKTUVjR0ExVUVBd3hBMEtiUXRkQzkwWUxSZ05DdzBMdlJqTkM5MExqUXVTRFF0OUN3MFlIUXN0R1cwTFRSaDlHRDBMTFFzTkM3MFl6UXZkQzQwTGtnMEw3UmdOQ3owTERRdlRFWk1CY0dBMVVFQlF3UVZVRXRORE15TWpBNE5URXRNakF5TURFTE1Ba0dBMVVFQmhNQ1ZVRXhFVEFQQmdOVkJBY01DTkNhMExqUmw5Q3lBaFFGNFo0czJTNmltUUlBQUFBQkFBQUE1QUFBQURBTkJnc3FoaVFDQVFFQkFRTUJBUVJBYUJBemtoTFBOTURySTV3NlZ3T2xENGl3bGp5eEZ3eE9zaXhENGVhV2NDVWRyOTY1UDI5VXVNR0dsaVhaVER3TEgvb0hKSW9LK3JFa0VzdHFtK1YwYktHQ0hDNHdnZ0dJQmdzcWhraUc5dzBCQ1JBQ0ZUR0NBWGN3Z2dGek1JSUJiekF3TUF3R0NpcUdKQUlCQVFFQkFnRUVJTTZxZXVmS1ZUeUU1dVhVU1I5elI0c3R2OVJjbVZ6YTJpUzFXUG1PMGUxM01JSUJPVENDQVIra2dnRWJNSUlCRnpGY01Gb0dBMVVFQ2d4VDBKelJsdEM5MFpiUmdkR0MwTFhSZ05HQjBZTFFzdEMrSU5HRzBMalJoTkdBMEw3UXN0QyswWmNnMFlMUmdOQ3cwTDNSZ2RHRTBMN1JnTkM4MExEUmh0R1cwWmNnMEtQUXV0R0EwTERSbDlDOTBMZ3hNVEF2QmdOVkJBc01LTkNRMExUUXZOR1cwTDNSbHRHQjBZTFJnTkN3MFlMUXZ0R0FJTkNHMEtMUW9TRFFwdENYMEo0eFNUQkhCZ05WQkFNTVFOQ20wTFhRdmRHQzBZRFFzTkM3MFl6UXZkQzQwTGtnMExmUXNOR0IwTExSbHRDMDBZZlJnOUN5MExEUXU5R00wTDNRdU5DNUlOQyswWURRczlDdzBMMHhHVEFYQmdOVkJBVU1FRlZCTFRRek1qSXdPRFV4TFRJd01qQXhDekFKQmdOVkJBWVRBbFZCTVJFd0R3WURWUVFIREFqUW10QzQwWmZRc2dJVUJlR2VMTmt1b3BrQkFBQUFBUUFBQU1FQUFBQXdnZ0dqQmdzcWhraUc5dzBCQ1JBQ0ZqR0NBWkl3Z2dHT01JSUJpS0dDQVlRd2dnR0FNSUlCZkRDQ0FYZ3dnZ0ZDb1lJQkxUQ0NBU2t4WERCYUJnTlZCQW9NVTlDYzBaYlF2ZEdXMFlIUmd0QzEwWURSZ2RHQzBMTFF2aURSaHRDNDBZVFJnTkMrMExMUXZ0R1hJTkdDMFlEUXNOQzkwWUhSaE5DKzBZRFF2TkN3MFliUmx0R1hJTkNqMExyUmdOQ3cwWmZRdmRDNE1URXdMd1lEVlFRTERDalFrTkMwMEx6Umx0QzkwWmJSZ2RHQzBZRFFzTkdDMEw3UmdDRFFodENpMEtFZzBLYlFsOUNlTVZzd1dRWURWUVFEREZKUFExTlFMZEdCMExYUmdOQ3kwTFhSZ0NEUXB0QzEwTDNSZ3RHQTBMRFF1OUdNMEwzUXVOQzVJTkMzMExEUmdkQ3kwWmJRdE5HSDBZUFFzdEN3MEx2UmpOQzkwTGpRdVNEUXZ0R0EwTFBRc05DOU1Sa3dGd1lEVlFRRkRCQlZRUzAwTXpJeU1EZzFNUzB5TURJd01Rc3dDUVlEVlFRR0V3SlZRVEVSTUE4R0ExVUVCd3dJMEpyUXVOR1gwTElZRHpJd01qSXdPVEF5TURrd09EUTRXakF3TUF3R0NpcUdKQUlCQVFFQkFnRUVJRmo0QkR4VGJOd1gyTkV2VUhVM203ZW90M2ZzdGxNK2tlRDJ2WWZjaFlOME1BQXdnZ1c2QmdzcWhraUc5dzBCQ1JBQ0Z6R0NCYWt3Z2dXbE1JSUZvVENDQlIyZ0F3SUJBZ0lVQmVHZUxOa3VvcGtCQUFBQUFRQUFBTUVBQUFBd0RRWUxLb1lrQWdFQkFRRURBUUV3Z2dFWE1Wd3dXZ1lEVlFRS0RGUFFuTkdXMEwzUmx0R0IwWUxRdGRHQTBZSFJndEN5MEw0ZzBZYlF1TkdFMFlEUXZ0Q3kwTDdSbHlEUmd0R0EwTERRdmRHQjBZVFF2dEdBMEx6UXNOR0cwWmJSbHlEUW85QzYwWURRc05HWDBMM1F1REV4TUM4R0ExVUVDd3dvMEpEUXROQzgwWmJRdmRHVzBZSFJndEdBMExEUmd0QyswWUFnMEliUW90Q2hJTkNtMEpmUW5qRkpNRWNHQTFVRUF3eEEwS2JRdGRDOTBZTFJnTkN3MEx2UmpOQzkwTGpRdVNEUXQ5Q3cwWUhRc3RHVzBMVFJoOUdEMExMUXNOQzcwWXpRdmRDNDBMa2cwTDdSZ05DejBMRFF2VEVaTUJjR0ExVUVCUXdRVlVFdE5ETXlNakE0TlRFdE1qQXlNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeU1CNFhEVEl3TURFeE5qRTRNemt3TUZvWERUTXdNREV4TmpFNE16a3dNRm93Z2dFWE1Wd3dXZ1lEVlFRS0RGUFFuTkdXMEwzUmx0R0IwWUxRdGRHQTBZSFJndEN5MEw0ZzBZYlF1TkdFMFlEUXZ0Q3kwTDdSbHlEUmd0R0EwTERRdmRHQjBZVFF2dEdBMEx6UXNOR0cwWmJSbHlEUW85QzYwWURRc05HWDBMM1F1REV4TUM4R0ExVUVDd3dvMEpEUXROQzgwWmJRdmRHVzBZSFJndEdBMExEUmd0QyswWUFnMEliUW90Q2hJTkNtMEpmUW5qRkpNRWNHQTFVRUF3eEEwS2JRdGRDOTBZTFJnTkN3MEx2UmpOQzkwTGpRdVNEUXQ5Q3cwWUhRc3RHVzBMVFJoOUdEMExMUXNOQzcwWXpRdmRDNDBMa2cwTDdSZ05DejBMRFF2VEVaTUJjR0ExVUVCUXdRVlVFdE5ETXlNakE0TlRFdE1qQXlNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeU1JSUJVVENDQVJJR0N5cUdKQUlCQVFFQkF3RUJNSUlCQVRDQnZEQVBBZ0lCcnpBSkFnRUJBZ0VEQWdFRkFnRUJCRGJ6eWtER2FhVGFGekZKeWhMRExhNFlhMU9zYThZMldaZmVycTZLMHRpSStiL1ZOQUZwVHZuRUp6Mk0vbTNDajNCcUQwa1F6Z01DTmovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLzdveGRVV0FDYWpBcHlUd0w0R3FpaC9McjREWkRIcVZFUVVFendRMmZJVjhsTVZETy8yWkhoZkNKb1FHV0ZDcG9rbnRlOEpKcmxwT2g0YUorSEx2ZXRVa0NDN0RBNDZhN2VlNmE2RXpnZGw1dW1JYUJFQ3AxdXRGOFR4d2dvREVsbnNqSDE2dDlsanJwTUEzS1IwNDJXdndKY3BPRi9qcGNnM0dGYlE2S0pkZkM4SGVvMlE0dFdUcUxCZWYwQkkrYmJqNnhYa0VBemtBQkRaNCtMckMxTVA4R3BIOEk0MTYwTm5tU3lDemoyNFZieWRzdlk0M09KUVlZVXh0c1hRNzFJZms2VVI4MWhnUjIxTXo5VGZNUGp1amdnRkVNSUlCUURBcEJnTlZIUTRFSWdRZ0JlR2VMTmt1b3BtOGVuYVBCMTJzVEt1a2pxTWxEbDdBV1kzSUtOK0FFYVl3S3dZRFZSMGpCQ1F3SW9BZ0JlR2VMTmt1b3BtOGVuYVBCMTJzVEt1a2pxTWxEbDdBV1kzSUtOK0FFYVl3RGdZRFZSMFBBUUgvQkFRREFnRUdNQmtHQTFVZElBRUIvd1FQTUEwd0N3WUpLb1lrQWdFQkFRSUNNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUl3SGdZSUt3WUJCUVVIQVFNQkFmOEVEekFOTUFzR0NTcUdKQUlCQVFFQ0FUQkNCZ05WSFI4RU96QTVNRGVnTmFBemhqRm9kSFJ3T2k4dlkzcHZMbWR2ZGk1MVlTOWtiM2R1Ykc5aFpDOWpjbXh6TDBOYVR5MHlNREl3TFVaMWJHd3VZM0pzTUVNR0ExVWRMZ1E4TURvd09LQTJvRFNHTW1oMGRIQTZMeTlqZW04dVoyOTJMblZoTDJSdmQyNXNiMkZrTDJOeWJITXZRMXBQTFRJd01qQXRSR1ZzZEdFdVkzSnNNQTBHQ3lxR0pBSUJBUUVCQXdFQkEyOEFCR3d5ZE5CN3FDaTBpNmVtQ1RvVHBESWFXaHVTcE13QXNNV0pka1hSRUloT2s1ODVLN1JuUHZ3eDcybGZIaGtmelBYbHJuakRIQnFXVkxUR29xQUl1dVBJYk5aenlCaThic1FTRzZ4d243SDExVFIwaFlDcG42UXh4bmVqb21tSlU4WG05Z1N6dXZ3NFA3d3NGVGt3Z2hNNUJnc3Foa2lHOXcwQkNSQUNHREdDRXlnd2doTWtvWUlUSURDQ0V4d3dnaE1ZTUlJQjdLR0NBUzB3Z2dFcE1Wd3dXZ1lEVlFRS0RGUFFuTkdXMEwzUmx0R0IwWUxRdGRHQTBZSFJndEN5MEw0ZzBZYlF1TkdFMFlEUXZ0Q3kwTDdSbHlEUmd0R0EwTERRdmRHQjBZVFF2dEdBMEx6UXNOR0cwWmJSbHlEUW85QzYwWURRc05HWDBMM1F1REV4TUM4R0ExVUVDd3dvMEpEUXROQzgwWmJRdmRHVzBZSFJndEdBMExEUmd0QyswWUFnMEliUW90Q2hJTkNtMEpmUW5qRmJNRmtHQTFVRUF3eFNUME5UVUMzUmdkQzEwWURRc3RDMTBZQWcwS2JRdGRDOTBZTFJnTkN3MEx2UmpOQzkwTGpRdVNEUXQ5Q3cwWUhRc3RHVzBMVFJoOUdEMExMUXNOQzcwWXpRdmRDNDBMa2cwTDdSZ05DejBMRFF2VEVaTUJjR0ExVUVCUXdRVlVFdE5ETXlNakE0TlRFdE1qQXlNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeUdBOHlNREl5TURrd01qQTVNRGcwT0Zvd2Z6QjlNR2d3REFZS0tvWWtBZ0VCQVFFQ0FRUWdpd0hndzhiVXFHT0I1R1dkbG5iUG9lUVVqd2VDYW5FNE4yZUk0Yjk3NWNVRUlBWGhuaXpaTHFLWnZIcDJqd2RkckV5cnBJNmpKUTVld0ZtTnlDamZnQkdtQWhRRjRaNHMyUzZpbVFJQUFBQUJBQUFBNUFBQUFJQUFHQTh5TURJeU1Ea3dNakE1TURnME9GcWhKekFsTUNNR0NTc0dBUVVGQnpBQkFnUVdCQlJXTUNaVzdvc1JwM0dkUE5zdVBrWVhlY2VqK2pBTkJnc3FoaVFDQVFFQkFRTUJBUU5EQUFSQSthZy9qelhZditsaFhmY3Fva25vSTBiL2dOWm5QaUlyVkpTc1hZZEN1RGZJY2RCYzBlbUxxNG53YlJ6YXpYYjhBdWlCcFc5VzJVajFjN05PcDVZYWRLQ0NFTkF3Z2hETU1JSUZ1akNDQlRhZ0F3SUJBZ0lVQmVHZUxOa3VvcGtDQUFBQUFRQUFBT1FBQUFBd0RRWUxLb1lrQWdFQkFRRURBUUV3Z2dFWE1Wd3dXZ1lEVlFRS0RGUFFuTkdXMEwzUmx0R0IwWUxRdGRHQTBZSFJndEN5MEw0ZzBZYlF1TkdFMFlEUXZ0Q3kwTDdSbHlEUmd0R0EwTERRdmRHQjBZVFF2dEdBMEx6UXNOR0cwWmJSbHlEUW85QzYwWURRc05HWDBMM1F1REV4TUM4R0ExVUVDd3dvMEpEUXROQzgwWmJRdmRHVzBZSFJndEdBMExEUmd0QyswWUFnMEliUW90Q2hJTkNtMEpmUW5qRkpNRWNHQTFVRUF3eEEwS2JRdGRDOTBZTFJnTkN3MEx2UmpOQzkwTGpRdVNEUXQ5Q3cwWUhRc3RHVzBMVFJoOUdEMExMUXNOQzcwWXpRdmRDNDBMa2cwTDdSZ05DejBMRFF2VEVaTUJjR0ExVUVCUXdRVlVFdE5ETXlNakE0TlRFdE1qQXlNREVMTUFrR0ExVUVCaE1DVlVFeEVUQVBCZ05WQkFjTUNOQ2EwTGpSbDlDeU1CNFhEVEl3TURZd016QTNORFV3TUZvWERUSTFNRFl3TXpBM05EVXdNRm93Z1pBeEZqQVVCZ05WQkFvTURkQ1UwSjhnSXRDVTBJYlFyeUl4SWpBZ0JnTlZCQU1NR1ZSVFVDM1JnZEMxMFlEUXN0QzEwWUFnSXRDVTBaYlJqeUl4R1RBWEJnTlZCQVVURUZWQkxUUXpNemsxTURNekxUSXdNREF4Q3pBSkJnTlZCQVlUQWxWQk1SRXdEd1lEVlFRSERBalFtdEM0MFpmUXNqRVhNQlVHQTFVRVlRd09UbFJTVlVFdE5ETXpPVFV3TXpNd2dmSXdnY2tHQ3lxR0pBSUJBUUVCQXdFQk1JRzVNSFV3QndJQ0FRRUNBUXdDQVFBRUlSQys0OXRxNnA0ZmhsZU1SY0VsbFArVUk1U24xemo1R0g1bEZRRnlsUFRPQVFJaEFJQUFBQUFBQUFBQUFBQUFBQUFBQUFCbldTRTY4WUxwaDlQaGR4U1FmVWNOQkNHMkQ5TFkzT2lwTkNQR0VCdktrY1I2QUg1c01Bc216VlZzbXc1OUlPOHBLZ0FFUUtuVzYwWHhQSENDZ01TV2V5TWZYcTMyV091a3dEY3BIVGpaYS9BbHlrNFgrT2x5RGNZVnREb29sMThMd2Q2alpEaTFaT29zRjUvUUVqNXR1UHJGZVFRREpBQUVJU2MyN00xTG9reVUrR2VDditUSmVMZkV1QW40NDBmTk96cWlrL0Y2OUFFekFhT0NBa1V3Z2dKQk1Da0dBMVVkRGdRaUJDQ2pCelA5NEs4citIemNzSXkzUmpRTWdjSmFaeEMxakFjdXdOVDhZV2sxeHpBT0JnTlZIUThCQWY4RUJBTUNCc0F3SVFZRFZSMGxCQm93R0FZSUt3WUJCUVVIQXdnR0RDc0dBUVFCZ1pkR0FRRUlIekE4QmdOVkhTQUVOVEF6TURFR0NTcUdKQUlCQVFFQ0FqQWtNQ0lHQ0NzR0FRVUZCd0lCRmhab2RIUndjem92TDJONmJ5NW5iM1l1ZFdFdlkzQnpNQzBHQTFVZEVRUW1NQ1NDRUdOaExtbHVabTl5YldwMWMzUXVkV0dCRUdOaFFHbHVabTl5YldwMWMzUXVkV0V3REFZRFZSMFRBUUgvQkFJd0FEQnlCZ2dyQmdFRkJRY0JBd1JtTUdRd0NBWUdCQUNPUmdFQk1BZ0dCZ1FBamtZQkJEQXFCZ1lFQUk1R0FRVXdJREFlRmhob2RIUndjem92TDJONmJ5NW5iM1l1ZFdFdllXSnZkWFFUQW1WdU1CVUdDQ3NHQVFVRkJ3c0NNQWtHQndRQWkreEpBUUl3Q3dZSktvWWtBZ0VCQVFJQk1Dc0dBMVVkSXdRa01DS0FJQVhobml6WkxxS1p2SHAyandkZHJFeXJwSTZqSlE1ZXdGbU55Q2pmZ0JHbU1FSUdBMVVkSHdRN01Ea3dONkExb0RPR01XaDBkSEE2THk5amVtOHVaMjkyTG5WaEwyUnZkMjVzYjJGa0wyTnliSE12UTFwUExUSXdNakF0Um5Wc2JDNWpjbXd3UXdZRFZSMHVCRHd3T2pBNG9EYWdOSVl5YUhSMGNEb3ZMMk42Ynk1bmIzWXVkV0V2Wkc5M2JteHZZV1F2WTNKc2N5OURXazh0TWpBeU1DMUVaV3gwWVM1amNtd3dQQVlJS3dZQkJRVUhBUUVFTURBdU1Dd0dDQ3NHQVFVRkJ6QUJoaUJvZEhSd09pOHZZM3B2TG1kdmRpNTFZUzl6WlhKMmFXTmxjeTl2WTNOd0x6QU5CZ3NxaGlRQ0FRRUJBUU1CQVFOdkFBUnNFZEhVRmNCRFlHVmZ1bDVPNkRjbjQyQVJoSjJ2QldRRElKZWVuOWxwVERRbEkvUnd3ZkxjZ1dHdDdVTVhURnFGaWtIT0RCd0k0SlpSMFltM0poTmdkV3lIK0k2RjZDdExsdDB1dk9jaWIydmtDNzZwL2g3OWhHVU5LeWtuNlpXcHorZk0xWTVvRzJOYlgxVUpNSUlGWlRDQ0JPR2dBd0lCQWdJVUJlR2VMTmt1b3BrQ0FBQUFBUUFBQU1RQUFBQXdEUVlMS29Za0FnRUJBUUVEQVFFd2dnRVhNVnd3V2dZRFZRUUtERlBRbk5HVzBMM1JsdEdCMFlMUXRkR0EwWUhSZ3RDeTBMNGcwWWJRdU5HRTBZRFF2dEN5MEw3Umx5RFJndEdBMExEUXZkR0IwWVRRdnRHQTBMelFzTkdHMFpiUmx5RFFvOUM2MFlEUXNOR1gwTDNRdURFeE1DOEdBMVVFQ3d3bzBKRFF0TkM4MFpiUXZkR1cwWUhSZ3RHQTBMRFJndEMrMFlBZzBJYlFvdENoSU5DbTBKZlFuakZKTUVjR0ExVUVBd3hBMEtiUXRkQzkwWUxSZ05DdzBMdlJqTkM5MExqUXVTRFF0OUN3MFlIUXN0R1cwTFRSaDlHRDBMTFFzTkM3MFl6UXZkQzQwTGtnMEw3UmdOQ3owTERRdlRFWk1CY0dBMVVFQlF3UVZVRXRORE15TWpBNE5URXRNakF5TURFTE1Ba0dBMVVFQmhNQ1ZVRXhFVEFQQmdOVkJBY01DTkNhMExqUmw5Q3lNQjRYRFRJd01ERXhOakl3TWpJd01Gb1hEVEkxTURFeE5qSXdNakl3TUZvd2dnRXBNVnd3V2dZRFZRUUtERlBRbk5HVzBMM1JsdEdCMFlMUXRkR0EwWUhSZ3RDeTBMNGcwWWJRdU5HRTBZRFF2dEN5MEw3Umx5RFJndEdBMExEUXZkR0IwWVRRdnRHQTBMelFzTkdHMFpiUmx5RFFvOUM2MFlEUXNOR1gwTDNRdURFeE1DOEdBMVVFQ3d3bzBKRFF0TkM4MFpiUXZkR1cwWUhSZ3RHQTBMRFJndEMrMFlBZzBJYlFvdENoSU5DbTBKZlFuakZiTUZrR0ExVUVBd3hTVDBOVFVDM1JnZEMxMFlEUXN0QzEwWUFnMEtiUXRkQzkwWUxSZ05DdzBMdlJqTkM5MExqUXVTRFF0OUN3MFlIUXN0R1cwTFRSaDlHRDBMTFFzTkM3MFl6UXZkQzQwTGtnMEw3UmdOQ3owTERRdlRFWk1CY0dBMVVFQlF3UVZVRXRORE15TWpBNE5URXRNakF5TURFTE1Ba0dBMVVFQmhNQ1ZVRXhFVEFQQmdOVkJBY01DTkNhMExqUmw5Q3lNSUh5TUlISkJnc3FoaVFDQVFFQkFRTUJBVENCdVRCMU1BY0NBZ0VCQWdFTUFnRUFCQ0VRdnVQYmF1cWVINFpYakVYQkpaVC9sQ09VcDljNCtSaCtaUlVCY3BUMHpnRUNJUUNBQUFBQUFBQUFBQUFBQUFBQUFBQUFaMWtoT3ZHQzZZZlQ0WGNVa0gxSERRUWh0Zy9TMk56b3FUUWp4aEFieXBIRWVnQitiREFMSnMxVmJKc09mU0R2S1NvQUJFQ3AxdXRGOFR4d2dvREVsbnNqSDE2dDlsanJwTUEzS1IwNDJXdndKY3BPRi9qcGNnM0dGYlE2S0pkZkM4SGVvMlE0dFdUcUxCZWYwQkkrYmJqNnhYa0VBeVFBQkNIRDR4VlNMb0ZUclcvTklHNmRKaWgxQlFEejRtTklSbXI3SXNGRGJSWHBMZ0NqZ2dGV01JSUJVakFwQmdOVkhRNEVJZ1FnemdwTENYYXRXQ1RubCtGaU1XUmdkYjhLN0F0RWplYWVBcU5NaFluOWN5TXdLd1lEVlIwakJDUXdJb0FnQmVHZUxOa3VvcG04ZW5hUEIxMnNUS3VranFNbERsN0FXWTNJS04rQUVhWXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1CWUdBMVVkSlFFQi93UU1NQW9HQ0NzR0FRVUZCd01KTUJrR0ExVWRJQUVCL3dRUE1BMHdDd1lKS29Za0FnRUJBUUlDTUF3R0ExVWRFd0VCL3dRQ01BQXdIZ1lJS3dZQkJRVUhBUU1CQWY4RUR6QU5NQXNHQ1NxR0pBSUJBUUVDQVRCQ0JnTlZIUjhFT3pBNU1EZWdOYUF6aGpGb2RIUndPaTh2WTNwdkxtZHZkaTUxWVM5a2IzZHViRzloWkM5amNteHpMME5hVHkweU1ESXdMVVoxYkd3dVkzSnNNRU1HQTFVZExnUThNRG93T0tBMm9EU0dNbWgwZEhBNkx5OWplbTh1WjI5MkxuVmhMMlJ2ZDI1c2IyRmtMMk55YkhNdlExcFBMVEl3TWpBdFJHVnNkR0V1WTNKc01BMEdDeXFHSkFJQkFRRUJBd0VCQTI4QUJHejltWFVma0tqV0lsbEpGQytvZDBWTGp0NFpZMEdUc2htTzFPZHBTekRoSVVFL3NDWUZDUlNkL0RZYk9KbkdvQ1VCZm84RW9ndlZXOWdvbVF2b1JFYWVxYjZpUUxNcml1NndkT1MxWkxSMEdSTlBxb1NQMHBmakxNT3NsWlNROHQ0QUxpRFhta3h0akdyem1SZ3dnZ1doTUlJRkhhQURBZ0VDQWhRRjRaNHMyUzZpbVFFQUFBQUJBQUFBd1FBQUFEQU5CZ3NxaGlRQ0FRRUJBUU1CQVRDQ0FSY3hYREJhQmdOVkJBb01VOUNjMFpiUXZkR1cwWUhSZ3RDMTBZRFJnZEdDMExMUXZpRFJodEM0MFlUUmdOQyswTExRdnRHWElOR0MwWURRc05DOTBZSFJoTkMrMFlEUXZOQ3cwWWJSbHRHWElOQ2owTHJSZ05DdzBaZlF2ZEM0TVRFd0x3WURWUVFMRENqUWtOQzAwTHpSbHRDOTBaYlJnZEdDMFlEUXNOR0MwTDdSZ0NEUWh0Q2kwS0VnMEtiUWw5Q2VNVWt3UndZRFZRUURERURRcHRDMTBMM1JndEdBMExEUXU5R00wTDNRdU5DNUlOQzMwTERSZ2RDeTBaYlF0TkdIMFlQUXN0Q3cwTHZSak5DOTBMalF1U0RRdnRHQTBMUFFzTkM5TVJrd0Z3WURWUVFGREJCVlFTMDBNekl5TURnMU1TMHlNREl3TVFzd0NRWURWUVFHRXdKVlFURVJNQThHQTFVRUJ3d0kwSnJRdU5HWDBMSXdIaGNOTWpBd01URTJNVGd6T1RBd1doY05NekF3TVRFMk1UZ3pPVEF3V2pDQ0FSY3hYREJhQmdOVkJBb01VOUNjMFpiUXZkR1cwWUhSZ3RDMTBZRFJnZEdDMExMUXZpRFJodEM0MFlUUmdOQyswTExRdnRHWElOR0MwWURRc05DOTBZSFJoTkMrMFlEUXZOQ3cwWWJSbHRHWElOQ2owTHJSZ05DdzBaZlF2ZEM0TVRFd0x3WURWUVFMRENqUWtOQzAwTHpSbHRDOTBaYlJnZEdDMFlEUXNOR0MwTDdSZ0NEUWh0Q2kwS0VnMEtiUWw5Q2VNVWt3UndZRFZRUURERURRcHRDMTBMM1JndEdBMExEUXU5R00wTDNRdU5DNUlOQzMwTERSZ2RDeTBaYlF0TkdIMFlQUXN0Q3cwTHZSak5DOTBMalF1U0RRdnRHQTBMUFFzTkM5TVJrd0Z3WURWUVFGREJCVlFTMDBNekl5TURnMU1TMHlNREl3TVFzd0NRWURWUVFHRXdKVlFURVJNQThHQTFVRUJ3d0kwSnJRdU5HWDBMSXdnZ0ZSTUlJQkVnWUxLb1lrQWdFQkFRRURBUUV3Z2dFQk1JRzhNQThDQWdHdk1Ba0NBUUVDQVFNQ0FRVUNBUUVFTnZQS1FNWnBwTm9YTVVuS0VzTXRyaGhyVTZ4cnhqWlpsOTZ1cm9yUzJJajV2OVUwQVdsTytjUW5QWXorYmNLUGNHb1BTUkRPQXdJMlAvLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vL3VqRjFSWUFKcU1DbkpQQXZnYXFLSDh1dmdOa01lcFVSQlFUUEJEWjhoWHlVeFVNNy9aa2VGOEltaEFaWVVLbWlTZTE3d2ttdVdrNkhob240Y3U5NjFTUUlMc01EanBydDU3cHJvVE9CMlhtNllob0VRS25XNjBYeFBIQ0NnTVNXZXlNZlhxMzJXT3Vrd0RjcEhUalphL0FseWs0WCtPbHlEY1lWdERvb2wxOEx3ZDZqWkRpMVpPb3NGNS9RRWo1dHVQckZlUVFET1FBRU5uajR1c0xVdy93YWtmd2pqWHJRMmVaTElMT1BiaFZ2SjJ5OWpqYzRsQmhoVEcyeGREdlVoK1RwUkh6V0dCSGJVelAxTjh3K082T0NBVVF3Z2dGQU1Da0dBMVVkRGdRaUJDQUY0WjRzMlM2aW1ieDZkbzhIWGF4TXE2U09veVVPWHNCWmpjZ28zNEFScGpBckJnTlZIU01FSkRBaWdDQUY0WjRzMlM2aW1ieDZkbzhIWGF4TXE2U09veVVPWHNCWmpjZ28zNEFScGpBT0JnTlZIUThCQWY4RUJBTUNBUVl3R1FZRFZSMGdBUUgvQkE4d0RUQUxCZ2txaGlRQ0FRRUJBZ0l3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQWpBZUJnZ3JCZ0VGQlFjQkF3RUIvd1FQTUEwd0N3WUpLb1lrQWdFQkFRSUJNRUlHQTFVZEh3UTdNRGt3TjZBMW9ET0dNV2gwZEhBNkx5OWplbTh1WjI5MkxuVmhMMlJ2ZDI1c2IyRmtMMk55YkhNdlExcFBMVEl3TWpBdFJuVnNiQzVqY213d1F3WURWUjB1QkR3d09qQTRvRGFnTklZeWFIUjBjRG92TDJONmJ5NW5iM1l1ZFdFdlpHOTNibXh2WVdRdlkzSnNjeTlEV2s4dE1qQXlNQzFFWld4MFlTNWpjbXd3RFFZTEtvWWtBZ0VCQVFFREFRRURid0FFYkRKMDBIdW9LTFNMcDZZSk9oT2tNaHBhRzVLa3pBQ3d4WWwyUmRFUWlFNlRuemtydEdjKy9ESHZhVjhlR1IvTTllV3VlTU1jR3BaVXRNYWlvQWk2NDhoczFuUElHTHh1eEJJYnJIQ2ZzZlhWTkhTRmdLbWZwREhHZDZPaWFZbFR4ZWIyQkxPNi9EZy92Q3dWT1E9PSJ9XX0=';
		//
		// let ress = Buffer.from(b64string, 'base64').toString('ascii');
		//
		// ress = JSON.parse(ress);
		//
		// let hash = 'oMI8kG9G9Inm1AhNPq6Akj5VaosHJubuRgTM+lZAFbo=';

		let signInfo = VerifyHash(hash, signature);
		// _printSignInfo(signInfo);
		console.log(`End IIT function VerifyHashSign`);
		return res.status(200).json(signInfo);
	} catch (err) {
		console.log(err);
		// log.error(`${err}`);
	}

});

app.listen(3050, function () {
	console.log('LISTENING IIT LIBRARY...');
})

// module.exports = {
//
// 	VerifyHashSign: (hash, signature) => {
// 		log.info(`Start IIT function VerifyHashSign`);
// 		try {
//
//
// 			let signInfo = VerifyHash('oMI8kG9G9Inm1AhNPq6Akj5VaosHJubuRgTM+lZAFbo=', ress.signedItems[0].signature);
//
// 			// _printSignInfo(signInfo);
// 			log.info(`End IIT function VerifyHashSign`);
// 			return signInfo;
// 		} catch (err) {
// 			console.log(err)
// 			log.error(`${err}`);
// 		}
//
// 	}
//
// }

module.exports = app;
